### ISSUE TITLE
Форматирование строк

### ISSUE THREAD

**Issue by paulin-mipt** [mountain-viewer/Facebook-ToDo-List-Bot#2]
Складывать строки -- зло. 

Используй функцию format, это уместнее почти всегда!

**Comment by paulin-mipt** [comment]
Например, здесь:

return "\n(" + "Title: " + self.name + "\n" +  "ID: "+ str(self.id) + "\n" + "Deadline: " + str(time_tuple) + ")\n"

**Comment by yarosl4v** [comment]
@paulin-mipt Окей, я поправлю. Спасибо!
