### ISSUE TITLE
Секьюрность и файлы в гитхабе

### ISSUE THREAD

**Issue by paulin-mipt** [mountain-viewer/Facebook-ToDo-List-Bot#3]
Хранить в гитхабе приватные токены -- сомнительная затея. Нужно выносить это в отдельный файл, импортировать его где-то в коде, а сам файл занести в .gitignore (в него же надо занести папку \_\_pycache\_\_, все бинарные файлы, файлы баз данных и прочее)

В истории гитхаба это уже останется навечно, но что поделать. Так оставлять тоже нельзя

**Comment by yarosl4v** [comment]
@paulin-mipt Я всё это прекрасно понимаю, просто уровень значимости сего проекта не столь высок для злоумышленников, поэтому я решил не запариваться особо сильно. Но спасибо за рекомендацию!
