### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by paulin-mipt** [mountain-viewer/Facebook-ToDo-List-Bot#4]
Есть хороший стандартный модуль logging. 
Его нужно применить по прямому назначению, а не логировать в stdout

**Comment by yarosl4v** [comment]
@paulin-mipt, спасибо

**Comment by paulin-mipt** [comment]
До сих пор пойманные тобой Exception пишут трейс в stdout. Есть ещё print в разных других местах. Не нужно одну информацию выводить в консоль, а другую в лог -- это неправильно. 

Логируй ошибки с соответствующим уровнем (warning/debug/critical), это же очень важная информация
